--<ScriptOptions statementTerminator=";"/>

ALTER TABLE "PUBLIC"."LOCATION_EVENTS" DROP CONSTRAINT "CONSTRAINT_C8";

ALTER TABLE "PUBLIC"."LOCATION_EVENTS" DROP CONSTRAINT "LOCATION_EVENTS_PK";

DROP INDEX "PUBLIC"."PRIMARY_KEY_C8BB1";

DROP INDEX "PUBLIC"."CONSTRAINT_C8_INDEX_9";

DROP INDEX "PUBLIC"."PRIMARY_KEY_C8";

DROP INDEX "PUBLIC"."PRIMARY_KEY_C8B";

DROP INDEX "PUBLIC"."PRIMARY_KEY_95";

DROP INDEX "PUBLIC"."PRIMARY_KEY_C";

DROP INDEX "PUBLIC"."PRIMARY_KEY_C8BB";

DROP INDEX "PUBLIC"."CONSTRAINT_C_INDEX_9";

DROP INDEX "PUBLIC"."PRIMARY_KEY_C8BB1CE";

DROP INDEX "PUBLIC"."PRIMARY_KEY_C8BB1C";

DROP TABLE "PUBLIC"."LOCATION_EVENTS";

CREATE TABLE "PUBLIC"."LOCATION_EVENTS" (
		"LOCATION_EVENTS_PID" INTEGER NOT NULL,
		"EVENT_PID" INTEGER NOT NULL,
		"LOCATION_PID" INTEGER NOT NULL,
		"PRIMARY_EVENT" BOOLEAN NOT NULL,
		"PRIMARY_LOCATION" BOOLEAN NOT NULL,
		"INSERT_TSTMP" TIMESTAMP NOT NULL,
		"UPDATE_TSTMP" TIMESTAMP NOT NULL,
		"TABLE_ID" INTEGER DEFAULT 4 NOT NULL
	);

CREATE UNIQUE INDEX  ON "PUBLIC"."LOCATION_EVENTS" ("LOCATION_EVENTS_PID" ASC);

CREATE INDEX  ON "PUBLIC"."LOCATION_EVENTS" ("LOCATION_PID" ASC);

CREATE INDEX  ON "PUBLIC"."LOCATION_EVENTS" ("EVENT_PID" ASC);

ALTER TABLE "PUBLIC"."LOCATION_EVENTS" ADD  PRIMARY KEY ("LOCATION_EVENTS_PID");

ALTER TABLE "PUBLIC"."LOCATION_EVENTS" ADD  FOREIGN KEY ("LOCATION_PID")
	REFERENCES "PUBLIC"."LOCATIONS" ("LOCATION_PID")
	ON DELETE RESTRICT
	ON UPDATE RESTRICT;
	
ALTER TABLE LOCATION_EVENTS ADD FOREIGN KEY (EVENT_PID) 
	REFERENCES EVENTS (EVENT_PID)
	ON DELETE RESTRICT
	ON UPDATE RESTRICT;

