--<ScriptOptions statementTerminator=";"/>

ALTER TABLE SEX_TYPES DROP CONSTRAINT DICTIONARY_SEX_TYPES_FK;

ALTER TABLE SEX_TYPES DROP CONSTRAINT SEX_TYPES_PK;

DROP INDEX PRIMARY_KEY_E;

DROP INDEX PRIMARY_KEY_E7EB;

DROP INDEX PRIMARY_KEY_E7E;

DROP INDEX PRIMARY_KEY_E7;

DROP INDEX DICTIONARY_SEX_TYPES_FK_INDEX_E;

DROP INDEX PRIMARY_KEY_A5;

DROP TABLE SEX_TYPES;

CREATE TABLE SEX_TYPES (
		SEX_TYPE_PID INTEGER NOT NULL,
		ABBREVIATION CHAR(1) NOT NULL,
		TABLE_ID INTEGER DEFAULT 1 NOT NULL,
		LABEL_PID INTEGER NOT NULL
	);

CREATE UNIQUE INDEX PRIMARY_KEY_E ON SEX_TYPES (SEX_TYPE_PID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_E7EB ON SEX_TYPES (SEX_TYPE_PID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_E7E ON SEX_TYPES (SEX_TYPE_PID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_E7 ON SEX_TYPES (SEX_TYPE_PID ASC);

CREATE INDEX DICTIONARY_SEX_TYPES_FK_INDEX_E ON SEX_TYPES (LABEL_PID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_A5 ON SEX_TYPES (SEX_TYPE_PID ASC);

ALTER TABLE SEX_TYPES ADD CONSTRAINT SEX_TYPES_PK PRIMARY KEY (SEX_TYPE_PID);

ALTER TABLE SEX_TYPES ADD CONSTRAINT DICTIONARY_SEX_TYPES_FK FOREIGN KEY (LABEL_PID)
	REFERENCES DICTIONARY (LABEL_PID)
	ON DELETE RESTRICT
	ON UPDATE RESTRICT;

