--<ScriptOptions statementTerminator=";"/>

ALTER TABLE LOCATION_NAME_MAPS DROP CONSTRAINT LOCATION_NAME_STYLES_LOCATION_NAME_MAPS_FK;

ALTER TABLE LOCATION_NAME_MAPS DROP CONSTRAINT LOCATION_NAME_MAPS_PK;

DROP INDEX PRIMARY_KEY_8FE54;

DROP INDEX PRIMARY_KEY_506;

DROP INDEX PRIMARY_KEY_8FE;

DROP INDEX PRIMARY_KEY_8;

DROP INDEX PRIMARY_KEY_8FE54F;

DROP INDEX CONSTRAINT_INDEX_5;

DROP INDEX PRIMARY_KEY_3;

DROP INDEX PRIMARY_KEY_50;

DROP INDEX PRIMARY_KEY_320;

DROP INDEX PRIMARY_KEY_8F;

DROP INDEX PRIMARY_KEY_8FE5;

DROP TABLE LOCATION_NAME_MAPS;

