--<ScriptOptions statementTerminator=";"/>

ALTER TABLE LANGUAGES DROP CONSTRAINT LANGUAGES_DICTIONARY_FK_INDEX_9;

ALTER TABLE LANGUAGES DROP CONSTRAINT CONSTRAINT_9;

ALTER TABLE LANGUAGES DROP CONSTRAINT PRIMARY_KEY_9;

DROP INDEX PRIMARY_KEY_9;

DROP INDEX PRIMARY_KEY_97;

DROP TABLE LANGUAGES;

