--<ScriptOptions statementTerminator=";"/>

ALTER TABLE SEX_TYPES DROP CONSTRAINT SEX_TYPES_PK;

DROP INDEX PRIMARY_KEY_E7EB;

DROP INDEX DICTIONARY_SEX_TYPES_FK_INDEX_E;

DROP INDEX PRIMARY_KEY_E7E;

DROP INDEX PRIMARY_KEY_E7;

DROP INDEX PRIMARY_KEY_A5;

DROP INDEX PRIMARY_KEY_E;

DROP TABLE SEX_TYPES;

