--<ScriptOptions statementTerminator=";"/>

CREATE TABLE SEX_TYPES (
		SEX_TYPE_PID INTEGER NOT NULL,
		ABBREVIATION CHAR(1) NOT NULL,
		LABEL VARCHAR(2147483647) NOT NULL,
		LANGUAGE_PID INTEGER NOT NULL
	);

CREATE INDEX CONSTRAINT_E7_INDEX_E ON SEX_TYPES (LANGUAGE_PID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_E ON SEX_TYPES (SEX_TYPE_PID ASC);

ALTER TABLE SEX_TYPES ADD CONSTRAINT CONSTRAINT_E PRIMARY KEY (SEX_TYPE_PID);

ALTER TABLE SEX_TYPES ADD CONSTRAINT PRIMARY_KEY_E UNIQUE (SEX_TYPE_PID);

ALTER TABLE SEX_TYPES ADD CONSTRAINT CONSTRAINT_E7 FOREIGN KEY (LANGUAGE_PID)
	REFERENCES LANGUAGES (LANGUAGE_PID)
	ON DELETE RESTRICT
	ON UPDATE RESTRICT;

