--<ScriptOptions statementTerminator=";"/>

ALTER TABLE SEXES DROP CONSTRAINT CONSTRAINT_4B2;

ALTER TABLE SEXES DROP CONSTRAINT PERSONS_SEXES_FK;

ALTER TABLE SEXES DROP CONSTRAINT CONSTRAINT_4B24;

ALTER TABLE SEXES DROP CONSTRAINT CONSTRAINT_4B;

DROP INDEX SEX_TYPES_SEXES_FK_INDEX_1;

DROP INDEX CONSTRAINT_INDEX_4B;

DROP INDEX PRIMARY_KEY_1C9;

DROP INDEX PERSONS_SEXES_FK_INDEX_1;

DROP INDEX PRIMARY_KEY_4B;

DROP INDEX CONSTRAINT_INDEX_4B2;

DROP TABLE SEXES;

