--<ScriptOptions statementTerminator=";"/>

ALTER TABLE EVENT_NAMES DROP CONSTRAINT EVENT_NAMES_PK;

DROP INDEX PRIMARY_KEY_D16F7923_0;

DROP INDEX PRIMARY_KEY_8D;

DROP INDEX PRIMARY_KEY_D16F;

DROP INDEX PRIMARY_KEY_D1;

DROP INDEX PRIMARY_KEY_D16F79;

DROP INDEX PRIMARY_KEY_D16;

DROP INDEX PRIMARY_KEY_D16F7;

DROP INDEX CONSTRAINT_INDEX_D;

DROP INDEX PRIMARY_KEY_D16F792;

DROP TABLE EVENT_NAMES;

