--<ScriptOptions statementTerminator=";"/>

ALTER TABLE DICTIONARY DROP CONSTRAINT LANGUAGES_DICTIONARY_FK;

DROP INDEX DICTIONARY_SEX_TYPES_FK_INDEX_3;

DROP INDEX LANGUAGES_DICTIONARY_FK_INDEX_3;

DROP TABLE DICTIONARY;

