ALTER TABLE PERSON_NAME_MAPS ADD FOREIGN KEY  (NAME_STYLE_PID) REFERENCES PERSON_NAME_STYLES(NAME_STYLE_PID);
ALTER TABLE LOCATION_NAME_MAPS ADD FOREIGN KEY  (LOCATION_NAME_STYLE_PID) REFERENCES LOCATION_NAME_STYLES(LOCATION_NAME_STYLE_PID);

