--<ScriptOptions statementTerminator=";"/>

CREATE TABLE PERSON_NAME_MAPS (
		NAME_MAP_PID INTEGER NOT NULL,
		NAME_STYLE_PID INTEGER NOT NULL,
		PART_NO INTEGER NOT NULL,
		LABEL_PID INTEGER NOT NULL,
		INSERT_TSTMP TIMESTAMP NOT NULL,
		UPDATE_TSTMP TIMESTAMP NOT NULL,
		TABLE_ID INTEGER DEFAULT 13 NOT NULL
	);

CREATE UNIQUE INDEX PRIMARY_KEY_B963 ON PERSON_NAME_MAPS (NAME_MAP_PID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_B96 ON PERSON_NAME_MAPS (NAME_MAP_PID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_B9 ON PERSON_NAME_MAPS (NAME_MAP_PID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_F1 ON PERSON_NAME_MAPS (NAME_MAP_PID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_B ON PERSON_NAME_MAPS (NAME_MAP_PID ASC);

CREATE INDEX PERSON_NAME_STYLES_NAME_MAPS_FK_INDEX_F ON PERSON_NAME_MAPS (NAME_STYLE_PID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_C4 ON PERSON_NAME_MAPS (NAME_MAP_PID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_F ON PERSON_NAME_MAPS (NAME_MAP_PID ASC);

ALTER TABLE PERSON_NAME_MAPS ADD CONSTRAINT CONSTRAINT_F PRIMARY KEY (NAME_MAP_PID);

