--<ScriptOptions statementTerminator=";"/>

CREATE TABLE PERSON_EVENTS (
		PERSON_EVENT_PID INTEGER NOT NULL,
		EVENT_PID INTEGER NOT NULL,
		PERSON_PID INTEGER NOT NULL,
		PRIMARY_PERSON BOOLEAN NOT NULL,
		PRIMARY_EVENT BOOLEAN NOT NULL,
		INSERT_TSTMP TIMESTAMP NOT NULL,
		UPDATE_TSTMP TIMESTAMP NOT NULL,
		TABLE_ID INTEGER DEFAULT 2 NOT NULL,
		LANGUAGE_PID INTEGER,
		ROLE_PID INTEGER NOT NULL,
		EVENT_ROLE_PID INTEGER NOT NULL
	);

CREATE INDEX CONSTRAINT_INDEX_4A ON PERSON_EVENTS (EVENT_PID ASC);

CREATE UNIQUE INDEX INDEX_4 ON PERSON_EVENTS (PERSON_EVENT_PID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_4 ON PERSON_EVENTS (PERSON_EVENT_PID ASC);

CREATE INDEX INDEX_4A ON PERSON_EVENTS (LANGUAGE_PID ASC);

ALTER TABLE PERSON_EVENTS ADD CONSTRAINT CONSTRAINT_4A PRIMARY KEY (PERSON_EVENT_PID);

ALTER TABLE PERSON_EVENTS ADD CONSTRAINT CONSTRAINT_4A9 FOREIGN KEY (EVENT_PID)
	REFERENCES EVENTS (EVENT_PID)
	ON DELETE RESTRICT
	ON UPDATE RESTRICT;

