--<ScriptOptions statementTerminator=";"/>

ALTER TABLE DICTIONARY DROP CONSTRAINT LANGUAGES_DICTIONARY_FK;

ALTER TABLE DICTIONARY DROP CONSTRAINT DICTIONARY_PK;

ALTER TABLE DICTIONARY DROP CONSTRAINT DICTIONARY_SEX_TYPES_FK_INDEX_3;

DROP INDEX PRIMARY_KEY_378F5;

DROP INDEX PRIMARY_KEY_378F;

DROP INDEX PRIMARY_KEY_378;

DROP INDEX DICTIONARY_SEX_TYPES_FK_INDEX_3;

DROP INDEX LANGUAGES_DICTIONARY_FK_INDEX_3;

DROP TABLE DICTIONARY;

