--<ScriptOptions statementTerminator=";"/>

ALTER TABLE "PUBLIC"."EVENTS" DROP CONSTRAINT "CONSTRAINT_7A";

ALTER TABLE "PUBLIC"."EVENTS" DROP CONSTRAINT "INDEX_7";

DROP INDEX "PUBLIC"."PRIMARY_KEY_DE";

DROP INDEX "PUBLIC"."INDEX_7";

DROP INDEX "PUBLIC"."INDEX_7A9";

DROP INDEX "PUBLIC"."INDEX_7A";

DROP TABLE "PUBLIC"."EVENTS";

CREATE TABLE "PUBLIC"."EVENTS" (
		"EVENT_PID" INTEGER NOT NULL,
		"INSERT_TSTMP" TIMESTAMP NOT NULL,
		"UPDATE_TSTMP" TIMESTAMP NOT NULL,
		"TABLE_ID" INTEGER DEFAULT 12 NOT NULL,
		"FROM_DATE_PID" INTEGER,
		"TO_DATE_PID" INTEGER,
		"EVENT_TYPE_PID" INTEGER NOT NULL
	);

CREATE UNIQUE INDEX "PUBLIC"."PRIMARY_KEY_DE" ON "PUBLIC"."EVENTS" ("EVENT_PID" ASC);

CREATE UNIQUE INDEX "PUBLIC"."INDEX_7" ON "PUBLIC"."EVENTS" ("EVENT_PID" ASC);

CREATE INDEX "PUBLIC"."INDEX_7A9" ON "PUBLIC"."EVENTS" ("FROM_DATE_PID" ASC);

CREATE INDEX "PUBLIC"."INDEX_7A" ON "PUBLIC"."EVENTS" ("TO_DATE_PID" ASC);

ALTER TABLE "PUBLIC"."EVENTS" ADD CONSTRAINT "CONSTRAINT_7A" PRIMARY KEY ("EVENT_PID");

ALTER TABLE "PUBLIC"."EVENTS" ADD CONSTRAINT "INDEX_7" UNIQUE ("EVENT_PID");

