--<ScriptOptions statementTerminator=";"/>

ALTER TABLE EVENTS DROP CONSTRAINT CONSTRAINT_7A9;

ALTER TABLE EVENTS DROP CONSTRAINT CONSTRAINT_7A9A;

ALTER TABLE EVENTS DROP CONSTRAINT CONSTRAINT_7A;

ALTER TABLE EVENTS DROP CONSTRAINT PRIMARY_KEY_7A9A;

DROP INDEX PRIMARY_KEY_DEE;

DROP INDEX PRIMARY_KEY_7A9A;

DROP INDEX PRIMARY_KEY_7A9;

DROP INDEX PRIMARY_KEY_7A9AD51;

DROP INDEX CONSTRAINT_7A9A_INDEX_D;

DROP INDEX CONSTRAINT_7A9_INDEX_D7;

DROP INDEX PRIMARY_KEY_7A9AD5;

DROP INDEX PRIMARY_KEY_7A9AD;

DROP INDEX PRIMARY_KEY_7A;

DROP INDEX PRIMARY_KEY_7;

DROP TABLE EVENTS;

