--<ScriptOptions statementTerminator=";"/>

ALTER TABLE NAMES DROP CONSTRAINT PERSON_NAME_STYLES_NAMES_FK;

ALTER TABLE NAMES DROP CONSTRAINT PERSONS_NAMES_FK;

ALTER TABLE NAMES DROP CONSTRAINT CONSTRAINT_469;

ALTER TABLE NAMES DROP CONSTRAINT CONSTRAINT_46;

ALTER TABLE NAMES DROP CONSTRAINT PRIMARY_KEY_46;

ALTER TABLE NAMES DROP CONSTRAINT CONSTRAINT_4;

DROP INDEX PERSONS_NAMES_FK_INDEX_1;

DROP INDEX PRIMARY_KEY_46;

DROP INDEX PRIMARY_KEY_469;

DROP INDEX PERSON_NAME_STYLES_NAMES_FK_INDEX_1;

DROP INDEX PRIMARY_KEY_1C;

DROP INDEX CONSTRAINT_INDEX_4;

DROP INDEX CONSTRAINT_INDEX_46;

DROP TABLE NAMES;

CREATE TABLE NAMES (
		NAME_PID INTEGER NOT NULL,
		PERSON_PID INTEGER NOT NULL,
		PRIMARY_NAME BOOLEAN,
		NAME_STYLE_PID INTEGER NOT NULL,
		TABLE_ID INTEGER DEFAULT 10 NOT NULL,
		FROM_DATE_PID INTEGER,
		TO_DATE_PID INTEGER
	);

CREATE INDEX PERSONS_NAMES_FK_INDEX_1 ON NAMES (PERSON_PID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_46 ON NAMES (NAME_PID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_469 ON NAMES (NAME_PID ASC);

CREATE INDEX PERSON_NAME_STYLES_NAMES_FK_INDEX_1 ON NAMES (NAME_STYLE_PID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_1C ON NAMES (NAME_PID ASC);

CREATE INDEX CONSTRAINT_INDEX_4 ON NAMES (FROM_DATE_PID ASC);

CREATE INDEX CONSTRAINT_INDEX_46 ON NAMES (TO_DATE_PID ASC);

ALTER TABLE NAMES ADD CONSTRAINT PRIMARY_KEY_46 UNIQUE (NAME_PID);

ALTER TABLE NAMES ADD CONSTRAINT CONSTRAINT_4 PRIMARY KEY (NAME_PID);

ALTER TABLE NAMES ADD CONSTRAINT PERSON_NAME_STYLES_NAMES_FK FOREIGN KEY (NAME_STYLE_PID)
	REFERENCES PERSON_NAME_STYLES (NAME_STYLE_PID)
	ON DELETE RESTRICT
	ON UPDATE RESTRICT;

ALTER TABLE NAMES ADD CONSTRAINT PERSONS_NAMES_FK FOREIGN KEY (PERSON_PID)
	REFERENCES PERSONS (PERSON_PID)
	ON DELETE RESTRICT
	ON UPDATE RESTRICT;

ALTER TABLE NAMES ADD CONSTRAINT CONSTRAINT_469 FOREIGN KEY (TO_DATE_PID)
	REFERENCES HDATES (HDATE_PID)
	ON DELETE RESTRICT
	ON UPDATE RESTRICT;

ALTER TABLE NAMES ADD CONSTRAINT CONSTRAINT_46 FOREIGN KEY (FROM_DATE_PID)
	REFERENCES HDATES (HDATE_PID)
	ON DELETE RESTRICT
	ON UPDATE RESTRICT;

