--<ScriptOptions statementTerminator=";"/>

ALTER TABLE DICTIONARY DROP CONSTRAINT LANGUAGES_DICTIONARY_FK;

DROP INDEX PRIMARY_KEY_378;

DROP INDEX LANGUAGES_DICTIONARY_FK_INDEX_3;

DROP INDEX DICTIONARY_SEX_TYPES_FK_INDEX_3;

