--<ScriptOptions statementTerminator=";"/>

ALTER TABLE LOCATION_NAME_MAPS DROP CONSTRAINT LOCATION_NAME_MAPS_PK;

DROP INDEX CONSTRAINT_INDEX_5;

DROP INDEX PRIMARY_KEY_8;

DROP INDEX PRIMARY_KEY_8F;

DROP TABLE LOCATION_NAME_MAPS;

CREATE TABLE LOCATION_NAME_MAPS (
		LOCATION_NAME_MAP_PID INTEGER NOT NULL,
		LOCATION_NAME_STYLE_PID INTEGER NOT NULL,
		PART_NO INTEGER NOT NULL,
		LABEL_PID INTEGER NOT NULL,
		INSERT_TSTMP TIMESTAMP NOT NULL,
		UPDATE_TSTMP TIMESTAMP NOT NULL,
		TABLE_ID INTEGER DEFAULT 21 NOT NULL
	);

CREATE INDEX CONSTRAINT_INDEX_5 ON LOCATION_NAME_MAPS (LOCATION_NAME_STYLE_PID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_8 ON LOCATION_NAME_MAPS (LOCATION_NAME_MAP_PID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_8F ON LOCATION_NAME_MAPS (LOCATION_NAME_MAP_PID ASC);

ALTER TABLE LOCATION_NAME_MAPS ADD CONSTRAINT LOCATION_NAME_MAPS_PK PRIMARY KEY (LOCATION_NAME_MAP_PID);

