--<ScriptOptions statementTerminator=";"/>

ALTER TABLE SEX_TYPES DROP CONSTRAINT DICTIONARY_SEX_TYPES_FK;

ALTER TABLE SEX_TYPES DROP CONSTRAINT PRIMARY_KEY_E;

ALTER TABLE SEX_TYPES DROP CONSTRAINT SEX_TYPES_PK;

DROP INDEX PRIMARY_KEY_A5;

DROP INDEX DICTIONARY_SEX_TYPES_FK_INDEX_A;

DROP INDEX PRIMARY_KEY_E;

DROP TABLE SEX_TYPES;

