--<ScriptOptions statementTerminator=";"/>

ALTER TABLE PERSON_EVENTS DROP CONSTRAINT CONSTRAINT_4A9;

ALTER TABLE PERSON_EVENTS DROP CONSTRAINT CONSTRAINT_4A;

DROP INDEX INDEX_4;

DROP INDEX PRIMARY_KEY_4;

DROP INDEX CONSTRAINT_INDEX_4A;

DROP INDEX INDEX_4A;

DROP TABLE PERSON_EVENTS;

