--<ScriptOptions statementTerminator=";"/>

CREATE TABLE LOCATION_EVENTS (
		LOCATION_EVENTS_PID INTEGER NOT NULL,
		EVENT_PID INTEGER NOT NULL,
		LOCATION_PID INTEGER NOT NULL,
		PRIMARY_EVENT BOOLEAN NOT NULL,
		PRIMARY_LOCATION BOOLEAN NOT NULL,
		INSERT_TSTMP TIMESTAMP NOT NULL,
		UPDATE_TSTMP TIMESTAMP NOT NULL,
		TABLE_ID INTEGER DEFAULT 4 NOT NULL
	);

CREATE UNIQUE INDEX PRIMARY_KEY_C8BB1 ON LOCATION_EVENTS (LOCATION_EVENTS_PID ASC);

CREATE INDEX CONSTRAINT_C8_INDEX_9 ON LOCATION_EVENTS (LOCATION_PID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_C8 ON LOCATION_EVENTS (LOCATION_EVENTS_PID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_C8B ON LOCATION_EVENTS (LOCATION_EVENTS_PID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_95 ON LOCATION_EVENTS (LOCATION_EVENTS_PID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_C ON LOCATION_EVENTS (LOCATION_EVENTS_PID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_C8BB ON LOCATION_EVENTS (LOCATION_EVENTS_PID ASC);

CREATE INDEX CONSTRAINT_C_INDEX_9 ON LOCATION_EVENTS (EVENT_PID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_C8BB1CE ON LOCATION_EVENTS (LOCATION_EVENTS_PID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_C8BB1C ON LOCATION_EVENTS (LOCATION_EVENTS_PID ASC);

ALTER TABLE LOCATION_EVENTS ADD CONSTRAINT LOCATION_EVENTS_PK PRIMARY KEY (LOCATION_EVENTS_PID);

ALTER TABLE LOCATION_EVENTS ADD CONSTRAINT CONSTRAINT_C8 FOREIGN KEY (LOCATION_PID)
	REFERENCES LOCATIONS (LOCATION_PID)
	ON DELETE RESTRICT
	ON UPDATE RESTRICT;

