--<ScriptOptions statementTerminator=";"/>

ALTER TABLE "PUBLIC"."PERSON_EVENTS" DROP CONSTRAINT "CONSTRAINT_4A94";

ALTER TABLE "PUBLIC"."PERSON_EVENTS" DROP CONSTRAINT "CONSTRAINT_4A9";

ALTER TABLE "PUBLIC"."PERSON_EVENTS" DROP CONSTRAINT "CONSTRAINT_4A";

DROP INDEX "PUBLIC"."PRIMARY_KEY_4A9494";

DROP INDEX "PUBLIC"."PRIMARY_KEY_4A9";

DROP INDEX "PUBLIC"."PRIMARY_KEY_1FE";

DROP INDEX "PUBLIC"."CONSTRAINT_4A94_INDEX_1";

DROP INDEX "PUBLIC"."PRIMARY_KEY_4A94";

DROP INDEX "PUBLIC"."PRIMARY_KEY_4A";

DROP INDEX "PUBLIC"."PRIMARY_KEY_4";

DROP INDEX "PUBLIC"."CONSTRAINT_4A9_INDEX_1";

DROP INDEX "PUBLIC"."CONSTRAINT_INDEX_4A";

DROP INDEX "PUBLIC"."PRIMARY_KEY_4A949";

DROP INDEX "PUBLIC"."PRIMARY_KEY_4A94943_0";

DROP TABLE "PUBLIC"."PERSON_EVENTS";

CREATE TABLE "PUBLIC"."PERSON_EVENTS" (
		"PERSON_EVENT_PID" INTEGER NOT NULL,
		"EVENT_PID" INTEGER NOT NULL,
		"PERSON_PID" INTEGER NOT NULL,
		"ROLE" VARCHAR(2147483647) NOT NULL,
		"PRIMARY_PERSON" BOOLEAN NOT NULL,
		"PRIMARY_EVENT" BOOLEAN NOT NULL,
		"INSERT_TSTMP" TIMESTAMP NOT NULL,
		"UPDATE_TSTMP" TIMESTAMP NOT NULL,
		"TABLE_ID" INTEGER DEFAULT 2 NOT NULL,
		"LANGUAGE_PID" INTEGER
	);

CREATE UNIQUE INDEX "PUBLIC"."PRIMARY_KEY_4A9494" ON "PUBLIC"."PERSON_EVENTS" ("PERSON_EVENT_PID" ASC);

CREATE UNIQUE INDEX "PUBLIC"."PRIMARY_KEY_4A9" ON "PUBLIC"."PERSON_EVENTS" ("PERSON_EVENT_PID" ASC);

CREATE UNIQUE INDEX "PUBLIC"."PRIMARY_KEY_1FE" ON "PUBLIC"."PERSON_EVENTS" ("PERSON_EVENT_PID" ASC);

CREATE INDEX "PUBLIC"."CONSTRAINT_4A94_INDEX_1" ON "PUBLIC"."PERSON_EVENTS" ("PERSON_PID" ASC);

CREATE UNIQUE INDEX "PUBLIC"."PRIMARY_KEY_4A94" ON "PUBLIC"."PERSON_EVENTS" ("PERSON_EVENT_PID" ASC);

CREATE UNIQUE INDEX "PUBLIC"."PRIMARY_KEY_4A" ON "PUBLIC"."PERSON_EVENTS" ("PERSON_EVENT_PID" ASC);

CREATE UNIQUE INDEX "PUBLIC"."PRIMARY_KEY_4" ON "PUBLIC"."PERSON_EVENTS" ("PERSON_EVENT_PID" ASC);

CREATE INDEX "PUBLIC"."CONSTRAINT_4A9_INDEX_1" ON "PUBLIC"."PERSON_EVENTS" ("EVENT_PID" ASC);

CREATE INDEX "PUBLIC"."CONSTRAINT_INDEX_4A" ON "PUBLIC"."PERSON_EVENTS" ("LANGUAGE_PID" ASC);

CREATE UNIQUE INDEX "PUBLIC"."PRIMARY_KEY_4A949" ON "PUBLIC"."PERSON_EVENTS" ("PERSON_EVENT_PID" ASC);

CREATE UNIQUE INDEX "PUBLIC"."PRIMARY_KEY_4A94943_0" ON "PUBLIC"."PERSON_EVENTS" ("PERSON_EVENT_PID" ASC);

ALTER TABLE "PUBLIC"."PERSON_EVENTS" ADD CONSTRAINT "CONSTRAINT_4A" PRIMARY KEY ("PERSON_EVENT_PID");

ALTER TABLE "PUBLIC"."PERSON_EVENTS" ADD CONSTRAINT "CONSTRAINT_4A94" FOREIGN KEY ("PERSON_PID")
	REFERENCES "PUBLIC"."PERSONS" ("PERSON_PID")
	ON DELETE RESTRICT
	ON UPDATE RESTRICT;

ALTER TABLE "PUBLIC"."PERSON_EVENTS" ADD CONSTRAINT "CONSTRAINT_4A9" FOREIGN KEY ("EVENT_PID")
	REFERENCES "PUBLIC"."EVENTS" ("EVENT_PID")
	ON DELETE RESTRICT
	ON UPDATE RESTRICT;

